version: '3.3'
services:
  neo4j:
    image: neo4j:latest
    container_name: "cmkg-neo4j-db"
    restart: always
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - ./db/neo4j-cyphers:/import
      - $HOME/neo4j/plugins:/plugins
      - $HOME/neo4j/logs:/logs
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENCE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/root
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_default__advertised__address=localhost
      - NEO4J_dbms_connector_bolt_enabled=true
      - NEO4J_dbms_routing_enabled=true
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4J_dbms_logs_debug_level=DEBUG
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_apoc_initializer_cypher=CALL apoc.cypher.runSchemaFile('file:///init_db_setup.cypher')
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*
      - NEO4JLABS_PLUGINS=["apoc", "n10s"]
    networks:
      - cmkg_net

  api:
    container_name: "cmkg-container"
    restart: always
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PW=root
    volumes:
      - .:/app
    links:
      - 'neo4j'
    depends_on:
      - 'neo4j'
    networks:
      - cmkg_net

networks:
  cmkg_net:
    driver: bridge
